name: tecsture
favicon: null
layout_spectrum: 0.06381933996453881
typography_spectrum: 0.549055008450523
title: Hair tecsture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070506'
    - '#b1906f'
    - '#faceb5'
    - '#c06086'
    - '#922227'
  brandStrength: 0.125
  lightness: 1
  saturation: 0.9567621499300003
  rhythmicContrast: 0.75
purpose: []
