name: tecsture
favicon: null
layout_spectrum: 0.06381933996453881
typography_spectrum: 0.549055008450523
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.24027363490313292
  lightness: 0.12706601875834167
  saturation: 0.9567621499300003
  rhythmicContrast: 0.3562999255955219
purpose: []
